# Site
name: 'Kulliyetu Neva'
description: ''
logo: '/assets/images/kulliyetu-nevâ-logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: ''

include: ["_pages"]
permalink: /:title/

authors:
    kulliyetuneva:
      name: Kulliyetu Neva
      site: kulliyetuneva.com
      twitter: https://twitter.com/kulliyetuneva
      avatar: /assets/images/kulliyetuneva_profil.jpg

collections:
  category:
    output: true

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: kulliyetuneva

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

  # all categories
  - scope:
      path: ""
      type: category
    values:
      layout: category

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, vendor]